services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rekon_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - rekon
    tty: true

  nginx:
    image: nginx:alpine
    container_name: rekon_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - rekon

  postgres:
    image: postgres:16
    container_name: rekon_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rekon
      POSTGRES_PASSWORD: rekon
      POSTGRES_DB: rekon
    volumes:
      - rekon_postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-testing-db.sh:/docker-entrypoint-initdb.d/init-testing-db.sh
    networks:
      - rekon

  redis:
    image: redis:7-alpine
    container_name: rekon_redis
    restart: unless-stopped
    networks:
      - rekon

networks:
  rekon:
    name: rekon_network

volumes:
  rekon_postgres_data:
